/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.TreeMap;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import slang.dictionary.SlangWord;

/**
 *
 * @author Admin
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    
    CardLayout mainCardLayout;
    SlangWord slHandler = null;
    int correctAnswer = 0;
    Random rd = new Random();
    public HomeFrame() {
        initComponents();
        slHandler = new SlangWord();
        this.setLocationRelativeTo(null);
        dlReset.setLocationRelativeTo(null);
        dlDelete.setLocationRelativeTo(null);
        dlConfirmAddSlangWord.setLocationRelativeTo(null);
        dlConfirmContinueQuiz.setLocationRelativeTo(null);
        mainCardLayout = (CardLayout)(pnMainCard.getLayout());
        btnSearchBySlang.setBackground(Color.white);
        mainCardLayout.show(pnMainCard, "pnSearchBySlang");
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        lbResult.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
        lbResultDefinition.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
        lbHistoryResult.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
        lbQuestion.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(5, 5, 5, 5)));
        lbResultRandom.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
        lbResultModify.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
        lbResult.setEditable(false);
        lbResultRandom.setEditable(false);
        lbQuestion.setEditable(false);
        lbResultDefinition.setEditable(false);
        lbHistoryResult.setEditable(false);
    }
    
    public void resetColorButton(){
        Color defaultColor = new Color(204, 204, 204);
        btnSearchBySlang.setBackground(defaultColor);
        btnSearchByDefinition.setBackground(defaultColor);
        btnHistory.setBackground(defaultColor);
        btnRandom.setBackground(defaultColor);
        btnaddNewSlangWord.setBackground(defaultColor);
        btnQuiz.setBackground(defaultColor);
        btnModify.setBackground(defaultColor);
    }
    
    public void resetData(){
        lbResultDefinition.setText("");
        lbResult.setText("");
        tbSlangWordAddNew.setText("");
        tbDefinitionAddNew.setText("");
        tbDefinition.setText("");
        tbSlangWord.setText("");
        tbSlangWordModify.setText("");
        lbResultRandom.setText("");
        lbResultModify.setText("");
        pnShowContentQuiz.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dlReset = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        btnOkeConfirmReset = new javax.swing.JButton();
        btnCloseConfirmReset = new javax.swing.JButton();
        dlDelete = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        btnOkeConfirmDelete = new javax.swing.JButton();
        btnCloseConfirmDelete = new javax.swing.JButton();
        dlConfirmAddSlangWord = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        btnOverWrite = new javax.swing.JButton();
        btnDuplicate = new javax.swing.JButton();
        btnCloseConfirmAdd = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        dlConfirmContinueQuiz = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        btnYesQuiz = new javax.swing.JButton();
        btnNoQuiz = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        panelSidebar = new javax.swing.JPanel();
        btnSearchByDefinition = new javax.swing.JButton();
        btnSearchBySlang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        btnaddNewSlangWord = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnMainCard = new javax.swing.JPanel();
        pnSearchBySlang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tbSlangWord = new javax.swing.JTextField();
        btnSearchKeySlang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbResult = new javax.swing.JTextArea();
        pnHistory = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lbHistoryResult = new javax.swing.JTextArea();
        pnRandom = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lbResultRandom = new javax.swing.JTextArea();
        btnRandomAction = new javax.swing.JButton();
        pnSearchByDefinition = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lbResultDefinition = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tbDefinition = new javax.swing.JTextField();
        btnSearchKeyDefinition = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pnModify = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tbSlangWordModify = new javax.swing.JTextField();
        btnSearchKeySlangModify = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        lbResultModify = new javax.swing.JTextArea();
        btnUpdateSlangWord = new javax.swing.JButton();
        btnDeleteSlangWord = new javax.swing.JButton();
        pnAddNewSlangWord = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        tbSlangWordAddNew = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbDefinitionAddNew = new javax.swing.JTextArea();
        btnActionAddSlangWord = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        pnQuiz = new javax.swing.JPanel();
        btnActionQuiz = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        rdSlangWord = new javax.swing.JRadioButton();
        rdDefinition = new javax.swing.JRadioButton();
        pnShowContentQuiz = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        lbQuestion = new javax.swing.JTextArea();
        btnAS1 = new javax.swing.JButton();
        btnAS3 = new javax.swing.JButton();
        btnAS2 = new javax.swing.JButton();
        btnAS4 = new javax.swing.JButton();

        dlReset.setTitle("Warning");
        dlReset.setIconImage(null);
        dlReset.setMinimumSize(new java.awt.Dimension(350, 150));
        dlReset.setModal(true);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Are you sure to reset the slang word list?");

        btnOkeConfirmReset.setBackground(new java.awt.Color(255, 0, 0));
        btnOkeConfirmReset.setText("OKE");
        btnOkeConfirmReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeConfirmResetActionPerformed(evt);
            }
        });

        btnCloseConfirmReset.setText("Close");
        btnCloseConfirmReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseConfirmResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlResetLayout = new javax.swing.GroupLayout(dlReset.getContentPane());
        dlReset.getContentPane().setLayout(dlResetLayout);
        dlResetLayout.setHorizontalGroup(
            dlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlResetLayout.createSequentialGroup()
                .addGroup(dlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlResetLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(dlResetLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnOkeConfirmReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnCloseConfirmReset, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        dlResetLayout.setVerticalGroup(
            dlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlResetLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addGap(27, 27, 27)
                .addGroup(dlResetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkeConfirmReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseConfirmReset, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dlReset.getAccessibleContext().setAccessibleDescription("");

        dlDelete.setTitle("Warning");
        dlDelete.setIconImage(null);
        dlDelete.setMinimumSize(new java.awt.Dimension(350, 150));
        dlDelete.setModal(true);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Are you sure to delete this slang word?");

        btnOkeConfirmDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnOkeConfirmDelete.setText("OKE");
        btnOkeConfirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkeConfirmDeleteActionPerformed(evt);
            }
        });

        btnCloseConfirmDelete.setText("Close");
        btnCloseConfirmDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseConfirmDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlDeleteLayout = new javax.swing.GroupLayout(dlDelete.getContentPane());
        dlDelete.getContentPane().setLayout(dlDeleteLayout);
        dlDeleteLayout.setHorizontalGroup(
            dlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlDeleteLayout.createSequentialGroup()
                .addGroup(dlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlDeleteLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel10))
                    .addGroup(dlDeleteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnOkeConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnCloseConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        dlDeleteLayout.setVerticalGroup(
            dlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlDeleteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addGap(27, 27, 27)
                .addGroup(dlDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOkeConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseConfirmDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dlConfirmAddSlangWord.setTitle("Notification");
        dlConfirmAddSlangWord.setIconImage(null);
        dlConfirmAddSlangWord.setMinimumSize(new java.awt.Dimension(450, 150));
        dlConfirmAddSlangWord.setModal(true);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("This Slang word already exists, please choose an option?");

        btnOverWrite.setBackground(new java.awt.Color(153, 255, 153));
        btnOverWrite.setText("Overwrite");
        btnOverWrite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOverWriteActionPerformed(evt);
            }
        });

        btnDuplicate.setBackground(new java.awt.Color(102, 153, 255));
        btnDuplicate.setText("Duplicate");
        btnDuplicate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDuplicateActionPerformed(evt);
            }
        });

        btnCloseConfirmAdd.setText("Close");
        btnCloseConfirmAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseConfirmAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlConfirmAddSlangWordLayout = new javax.swing.GroupLayout(dlConfirmAddSlangWord.getContentPane());
        dlConfirmAddSlangWord.getContentPane().setLayout(dlConfirmAddSlangWordLayout);
        dlConfirmAddSlangWordLayout.setHorizontalGroup(
            dlConfirmAddSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlConfirmAddSlangWordLayout.createSequentialGroup()
                .addGroup(dlConfirmAddSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dlConfirmAddSlangWordLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel14))
                    .addGroup(dlConfirmAddSlangWordLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnOverWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnDuplicate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnCloseConfirmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dlConfirmAddSlangWordLayout.setVerticalGroup(
            dlConfirmAddSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlConfirmAddSlangWordLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addGap(27, 27, 27)
                .addGroup(dlConfirmAddSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOverWrite, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDuplicate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCloseConfirmAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dlConfirmContinueQuiz.setTitle("Notification");
        dlConfirmContinueQuiz.setIconImage(null);
        dlConfirmContinueQuiz.setMinimumSize(new java.awt.Dimension(400, 150));
        dlConfirmContinueQuiz.setModal(true);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("The answer is incorrect, do you want to continue?");

        btnYesQuiz.setBackground(new java.awt.Color(153, 255, 153));
        btnYesQuiz.setText("Yes");
        btnYesQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesQuizActionPerformed(evt);
            }
        });

        btnNoQuiz.setText("No");
        btnNoQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoQuizActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dlConfirmContinueQuizLayout = new javax.swing.GroupLayout(dlConfirmContinueQuiz.getContentPane());
        dlConfirmContinueQuiz.getContentPane().setLayout(dlConfirmContinueQuizLayout);
        dlConfirmContinueQuizLayout.setHorizontalGroup(
            dlConfirmContinueQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlConfirmContinueQuizLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dlConfirmContinueQuizLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnYesQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        dlConfirmContinueQuizLayout.setVerticalGroup(
            dlConfirmContinueQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dlConfirmContinueQuizLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(dlConfirmContinueQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNoQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYesQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);

        panelSidebar.setBackground(new java.awt.Color(102, 153, 255));

        btnSearchByDefinition.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchByDefinition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchByDefinition.setText("Search by definition");
        btnSearchByDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByDefinitionActionPerformed(evt);
            }
        });

        btnSearchBySlang.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchBySlang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchBySlang.setText("Search by slang word");
        btnSearchBySlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySlangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Slang Dictionnary");

        btnHistory.setBackground(new java.awt.Color(204, 204, 204));
        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHistory.setText("View search history");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnaddNewSlangWord.setBackground(new java.awt.Color(204, 204, 204));
        btnaddNewSlangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnaddNewSlangWord.setText("Add slang word");
        btnaddNewSlangWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddNewSlangWordActionPerformed(evt);
            }
        });

        btnModify.setBackground(new java.awt.Color(204, 204, 204));
        btnModify.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModify.setText("Update and delete slang word");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnRandom.setBackground(new java.awt.Color(204, 204, 204));
        btnRandom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRandom.setText("Random slang word");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnQuiz.setBackground(new java.awt.Color(204, 204, 204));
        btnQuiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuiz.setText("Quiz");
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 0, 0));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setText("Reset slang word list");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnaddNewSlangWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSearchBySlang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnaddNewSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModify, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelSidebar);

        pnMainCard.setLayout(new java.awt.CardLayout());

        pnSearchBySlang.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Input slang word:");

        tbSlangWord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSearchKeySlang.setBackground(new java.awt.Color(102, 153, 255));
        btnSearchKeySlang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchKeySlang.setText("Search");
        btnSearchKeySlang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchKeySlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeySlangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Search Result");

        lbResult.setBackground(new java.awt.Color(102, 153, 255));
        lbResult.setColumns(20);
        lbResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResult.setLineWrap(true);
        lbResult.setRows(5);
        lbResult.setWrapStyleWord(true);
        lbResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(lbResult);

        javax.swing.GroupLayout pnSearchBySlangLayout = new javax.swing.GroupLayout(pnSearchBySlang);
        pnSearchBySlang.setLayout(pnSearchBySlangLayout);
        pnSearchBySlangLayout.setHorizontalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                .addGroup(pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchKeySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel3))
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnSearchBySlangLayout.setVerticalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKeySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pnMainCard.add(pnSearchBySlang, "pnSearchBySlang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("The history of the slang words searched");

        lbHistoryResult.setBackground(new java.awt.Color(102, 153, 255));
        lbHistoryResult.setColumns(20);
        lbHistoryResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHistoryResult.setLineWrap(true);
        lbHistoryResult.setRows(5);
        lbHistoryResult.setWrapStyleWord(true);
        lbHistoryResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(lbHistoryResult);

        javax.swing.GroupLayout pnHistoryLayout = new javax.swing.GroupLayout(pnHistory);
        pnHistory.setLayout(pnHistoryLayout);
        pnHistoryLayout.setHorizontalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHistoryLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(jLabel6)
                .addContainerGap(178, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        pnHistoryLayout.setVerticalGroup(
            pnHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHistoryLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnMainCard.add(pnHistory, "pnHistory");

        lbResultRandom.setBackground(new java.awt.Color(102, 153, 255));
        lbResultRandom.setColumns(20);
        lbResultRandom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResultRandom.setLineWrap(true);
        lbResultRandom.setRows(5);
        lbResultRandom.setWrapStyleWord(true);
        lbResultRandom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(lbResultRandom);

        btnRandomAction.setBackground(new java.awt.Color(153, 255, 153));
        btnRandomAction.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRandomAction.setText("Click Here to random slang word");
        btnRandomAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnRandomLayout = new javax.swing.GroupLayout(pnRandom);
        pnRandom.setLayout(pnRandomLayout);
        pnRandomLayout.setHorizontalGroup(
            pnRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnRandomLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(pnRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRandomLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRandomLayout.createSequentialGroup()
                        .addComponent(btnRandomAction, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        pnRandomLayout.setVerticalGroup(
            pnRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnRandomLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRandomAction, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pnMainCard.add(pnRandom, "pnRandom");

        pnSearchByDefinition.setName(""); // NOI18N

        lbResultDefinition.setBackground(new java.awt.Color(102, 153, 255));
        lbResultDefinition.setColumns(20);
        lbResultDefinition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResultDefinition.setLineWrap(true);
        lbResultDefinition.setRows(5);
        lbResultDefinition.setWrapStyleWord(true);
        lbResultDefinition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(lbResultDefinition);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Input definition:");

        tbDefinition.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSearchKeyDefinition.setBackground(new java.awt.Color(102, 153, 255));
        btnSearchKeyDefinition.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchKeyDefinition.setText("Search");
        btnSearchKeyDefinition.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchKeyDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeyDefinitionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Search Result");

        javax.swing.GroupLayout pnSearchByDefinitionLayout = new javax.swing.GroupLayout(pnSearchByDefinition);
        pnSearchByDefinition.setLayout(pnSearchByDefinitionLayout);
        pnSearchByDefinitionLayout.setHorizontalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchByDefinitionLayout.createSequentialGroup()
                .addGroup(pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSearchByDefinitionLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSearchKeyDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSearchByDefinitionLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel5))
                    .addGroup(pnSearchByDefinitionLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        pnSearchByDefinitionLayout.setVerticalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchByDefinitionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKeyDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(46, 46, 46)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pnMainCard.add(pnSearchByDefinition, "pnSearchByDefinition");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Input slang word:");

        tbSlangWordModify.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSearchKeySlangModify.setBackground(new java.awt.Color(102, 153, 255));
        btnSearchKeySlangModify.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchKeySlangModify.setText("Search");
        btnSearchKeySlangModify.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchKeySlangModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeySlangModifyActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Edit slang word definitions");

        lbResultModify.setBackground(new java.awt.Color(102, 153, 255));
        lbResultModify.setColumns(20);
        lbResultModify.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResultModify.setLineWrap(true);
        lbResultModify.setRows(5);
        lbResultModify.setWrapStyleWord(true);
        lbResultModify.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(lbResultModify);

        btnUpdateSlangWord.setBackground(new java.awt.Color(153, 255, 153));
        btnUpdateSlangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateSlangWord.setText("Update");
        btnUpdateSlangWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSlangWordActionPerformed(evt);
            }
        });

        btnDeleteSlangWord.setBackground(new java.awt.Color(255, 0, 0));
        btnDeleteSlangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDeleteSlangWord.setText("Delete");
        btnDeleteSlangWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteSlangWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnModifyLayout = new javax.swing.GroupLayout(pnModify);
        pnModify.setLayout(pnModifyLayout);
        pnModifyLayout.setHorizontalGroup(
            pnModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModifyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbSlangWordModify, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchKeySlangModify, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(pnModifyLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnUpdateSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(pnModifyLayout.createSequentialGroup()
                .addGroup(pnModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnModifyLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(jLabel9))
                    .addGroup(pnModifyLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        pnModifyLayout.setVerticalGroup(
            pnModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnModifyLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tbSlangWordModify, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKeySlangModify, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(pnModifyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdateSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnMainCard.add(pnModify, "pnModify");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Input slang word:");

        tbSlangWordAddNew.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Input definitions:");

        tbDefinitionAddNew.setColumns(20);
        tbDefinitionAddNew.setLineWrap(true);
        tbDefinitionAddNew.setRows(5);
        tbDefinitionAddNew.setWrapStyleWord(true);
        tbDefinitionAddNew.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(tbDefinitionAddNew);

        btnActionAddSlangWord.setBackground(new java.awt.Color(153, 255, 153));
        btnActionAddSlangWord.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActionAddSlangWord.setText("Add slang word");
        btnActionAddSlangWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionAddSlangWordActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Notice: the definitions are separated by the character \",\"");

        javax.swing.GroupLayout pnAddNewSlangWordLayout = new javax.swing.GroupLayout(pnAddNewSlangWord);
        pnAddNewSlangWord.setLayout(pnAddNewSlangWordLayout);
        pnAddNewSlangWordLayout.setHorizontalGroup(
            pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddNewSlangWordLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActionAddSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tbSlangWordAddNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        pnAddNewSlangWordLayout.setVerticalGroup(
            pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnAddNewSlangWordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tbSlangWordAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnAddNewSlangWordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnAddNewSlangWordLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel12))
                    .addGroup(pnAddNewSlangWordLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(38, 38, 38)
                .addComponent(btnActionAddSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnMainCard.add(pnAddNewSlangWord, "pnAddNewSlangWord");

        btnActionQuiz.setBackground(new java.awt.Color(153, 255, 153));
        btnActionQuiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnActionQuiz.setText("Start");
        btnActionQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionQuizActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 153, 255)), "Quiz with", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(102, 153, 255))); // NOI18N

        buttonGroup1.add(rdSlangWord);
        rdSlangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdSlangWord.setSelected(true);
        rdSlangWord.setText("Slang word");

        buttonGroup1.add(rdDefinition);
        rdDefinition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdDefinition.setText("Definition");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rdSlangWord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdDefinition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdSlangWord)
                    .addComponent(rdDefinition))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lbQuestion.setColumns(20);
        lbQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbQuestion.setLineWrap(true);
        lbQuestion.setRows(5);
        lbQuestion.setWrapStyleWord(true);
        lbQuestion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbQuestion.setMinimumSize(new java.awt.Dimension(30, 10));
        jScrollPane7.setViewportView(lbQuestion);

        btnAS1.setBackground(new java.awt.Color(204, 204, 204));
        btnAS1.setToolTipText("");
        btnAS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAS1ActionPerformed(evt);
            }
        });

        btnAS3.setBackground(new java.awt.Color(204, 204, 204));
        btnAS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAS3ActionPerformed(evt);
            }
        });

        btnAS2.setBackground(new java.awt.Color(204, 204, 204));
        btnAS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAS2ActionPerformed(evt);
            }
        });

        btnAS4.setBackground(new java.awt.Color(204, 204, 204));
        btnAS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAS4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnShowContentQuizLayout = new javax.swing.GroupLayout(pnShowContentQuiz);
        pnShowContentQuiz.setLayout(pnShowContentQuizLayout);
        pnShowContentQuizLayout.setHorizontalGroup(
            pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnShowContentQuizLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAS1, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(btnAS3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAS2, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(btnAS4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnShowContentQuizLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pnShowContentQuizLayout.setVerticalGroup(
            pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnShowContentQuizLayout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAS1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAS2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnShowContentQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAS3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAS4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnQuizLayout = new javax.swing.GroupLayout(pnQuiz);
        pnQuiz.setLayout(pnQuizLayout);
        pnQuizLayout.setHorizontalGroup(
            pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuizLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(btnActionQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuizLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(pnShowContentQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        pnQuizLayout.setVerticalGroup(
            pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnQuizLayout.createSequentialGroup()
                .addGroup(pnQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnQuizLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnQuizLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnActionQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(pnShowContentQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnMainCard.add(pnQuiz, "pnQuiz");

        jSplitPane1.setRightComponent(pnMainCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBySlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySlangActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchBySlang");
        resetColorButton();
        resetData();
        btnSearchBySlang.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchBySlangActionPerformed

    private void btnSearchByDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByDefinitionActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchByDefinition");
        resetColorButton();
        resetData();
        btnSearchByDefinition.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchByDefinitionActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        resetData();
        mainCardLayout.show(pnMainCard, "pnHistory");
        resetColorButton();
        btnHistory.setBackground(Color.white);
        String rs = "";
        List<String> listDataHistory = slHandler.initHistoryData();
        for (int i = 0; i < listDataHistory.size(); i++){
            rs += listDataHistory.get(i) + "\n";
        }
        lbHistoryResult.setText(rs);
        
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnaddNewSlangWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddNewSlangWordActionPerformed
        // TODO add your handling code here:
        resetData();
        mainCardLayout.show(pnMainCard, "pnAddNewSlangWord");
        resetColorButton();
        btnaddNewSlangWord.setBackground(Color.white);
        
    }//GEN-LAST:event_btnaddNewSlangWordActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
        resetData();
        mainCardLayout.show(pnMainCard, "pnRandom");
        resetColorButton();
        btnRandom.setBackground(Color.white);
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // TODO add your handling code here:
        resetData();
        mainCardLayout.show(pnMainCard, "pnModify");
        resetColorButton();
        btnModify.setBackground(Color.white);
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        // TODO add your handling code here:
        resetData();
        mainCardLayout.show(pnMainCard, "pnQuiz");
        resetColorButton();
        btnQuiz.setBackground(Color.white);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        dlReset.setVisible(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchKeyDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeyDefinitionActionPerformed
        // TODO add your handling code here:
        lbResultDefinition.setText("");
        if (tbDefinition.getText().compareTo("") == 0){
            return;
        }
        List<String> listSlangWord = slHandler.getDataByDefinition(tbDefinition.getText());
        if (listSlangWord.size() == 0){  
            lbResultDefinition.setText("Sorry, no slang words were found with the definition '" + 
                    tbDefinition.getText() + "' :((");
            lbResultDefinition.setForeground(Color.RED);
        }
        else{
            String result = "Slang words of definition '" + tbDefinition.getText() + "': ";
            for (int i = 0; i < listSlangWord.size(); i++){
                result += listSlangWord.get(i);
                if (i != listSlangWord.size() - 1){
                    result += ", ";
                }
            }
            lbResultDefinition.setText(result);
            lbResultDefinition.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_btnSearchKeyDefinitionActionPerformed

    private void btnCloseConfirmResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseConfirmResetActionPerformed
        // TODO add your handling code here:
        dlReset.setVisible(false);
    }//GEN-LAST:event_btnCloseConfirmResetActionPerformed

    private void btnOkeConfirmResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeConfirmResetActionPerformed
        // TODO add your handling code here:
        try {
            slHandler.resetData();
            dlReset.setVisible(false);
            slHandler = new SlangWord();
            JOptionPane.showMessageDialog(null, "Reset was successful!!!");  
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnOkeConfirmResetActionPerformed

    private void btnSearchKeySlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeySlangActionPerformed
        // TODO add your handling code here:
        lbResult.setText("");
        if (tbSlangWord.getText().compareTo("") == 0){
            return;
        }
        String[] listDefinition = slHandler.getDataBySlangWord(tbSlangWord.getText());
        if (listDefinition == null){
            lbResult.setText("Sorry, no slang words were found with key word '" +
                tbSlangWord.getText() + "' :((");
            lbResult.setForeground(Color.RED);
        }
        else{
            String result = "Definitons of '" + tbSlangWord.getText() + "': ";
            for (int i = 0; i < listDefinition.length; i++){
                result += listDefinition[i];
                if (i != listDefinition.length - 1){
                    result += ", ";
                }
            }
            lbResult.setText(result);
            lbResult.setForeground(Color.BLACK);
        }
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm");  
        LocalDateTime now = LocalDateTime.now();
        String timeHistory = dtf.format(now) + " : " + tbSlangWord.getText(); 
        slHandler.saveHistoryData(timeHistory);
    }//GEN-LAST:event_btnSearchKeySlangActionPerformed

    private void btnRandomActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionActionPerformed
        // TODO add your handling code here:
        List<String> resultData = slHandler.randomSlangWords();
        if (resultData.size() == 0){
            JOptionPane.showMessageDialog(null, "Sorry, there is no slang word for random!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String rs = "Slang word: " + resultData.get(0) + "\n" + "Definitions: ";
        for (int i = 1; i < resultData.size(); i++){
            rs += resultData.get(i);
            if (i != resultData.size() - 1){
                rs += ", ";
            }
        }
        lbResultRandom.setText(rs);
    }//GEN-LAST:event_btnRandomActionActionPerformed

    private void btnSearchKeySlangModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeySlangModifyActionPerformed
        // TODO add your handling code here:
        lbResultModify.setText("");
        if (tbSlangWordModify.getText().compareTo("") == 0){
            tbSlangWordModify.setText("");
            return;
        }
        String[] listDefinition = slHandler.getDataBySlangWord(tbSlangWordModify.getText());
        if (listDefinition == null){
            JOptionPane.showMessageDialog(null, "No slang word found with the keyword entered!!!", "Error", JOptionPane.ERROR_MESSAGE);
            tbSlangWordModify.setText("");
        }
        else{
            String result = "";
            for (int i = 0; i < listDefinition.length; i++){
                result += listDefinition[i];
                if (i != listDefinition.length - 1){
                    result += ", ";
                }
            }
            lbResultModify.setText(result);
        }
    }//GEN-LAST:event_btnSearchKeySlangModifyActionPerformed

    private void btnDeleteSlangWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteSlangWordActionPerformed
        // TODO add your handling code here:
        if (tbSlangWordModify.getText().compareTo("") == 0){
            return;
        }       
        dlDelete.setVisible(true);
    }//GEN-LAST:event_btnDeleteSlangWordActionPerformed

    private void btnUpdateSlangWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSlangWordActionPerformed
        // TODO add your handling code here:
        if (tbSlangWordModify.getText().compareTo("") == 0){
            return;
        }
        if (lbResultModify.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Definitions cannot be empty!!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String key = tbSlangWordModify.getText();
        String newData = lbResultModify.getText();
        
        boolean resultUpdate = slHandler.updateSlangWord(key, newData);
        if (resultUpdate){
            JOptionPane.showMessageDialog(null, "Update was successful!!!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Update failed!!!", "Error", JOptionPane.ERROR_MESSAGE);
            lbResultModify.setText("");
        }
        
    }//GEN-LAST:event_btnUpdateSlangWordActionPerformed

    private void btnOkeConfirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkeConfirmDeleteActionPerformed
        // TODO add your handling code here:
        dlDelete.setVisible(false);
        boolean resultDelete = slHandler.deleteSlangWord(tbSlangWordModify.getText());
        if (resultDelete){
            JOptionPane.showMessageDialog(null, "Delete was successful!!!");
            tbSlangWordModify.setText("");
            lbResultModify.setText("");
        }
        else{
            JOptionPane.showMessageDialog(null, "Delete failed!!!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOkeConfirmDeleteActionPerformed

    private void btnCloseConfirmDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseConfirmDeleteActionPerformed
        // TODO add your handling code here:
        dlDelete.setVisible(false);
    }//GEN-LAST:event_btnCloseConfirmDeleteActionPerformed

    private void btnActionAddSlangWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionAddSlangWordActionPerformed
        // TODO add your handling code here:
        if (tbSlangWordAddNew.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Slang word cannot be empty!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (tbDefinitionAddNew.getText().compareTo("") == 0){
            JOptionPane.showMessageDialog(null, "Definitions cannot be empty!!!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (slHandler.checkSlangWordExist(tbSlangWordAddNew.getText())){
            dlConfirmAddSlangWord.setVisible(true);
        }
        else{
            slHandler.addSlangWord(tbSlangWordAddNew.getText(), tbDefinitionAddNew.getText(), 0);
            JOptionPane.showMessageDialog(null, "Added slang word successfully!!!");
            resetData();
        }
    }//GEN-LAST:event_btnActionAddSlangWordActionPerformed

    private void btnOverWriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOverWriteActionPerformed
        // TODO add your handling code here:
        slHandler.addSlangWord(tbSlangWordAddNew.getText(), tbDefinitionAddNew.getText(), 1);
        dlConfirmAddSlangWord.setVisible(false);
        JOptionPane.showMessageDialog(null, "Overwrite slang word successfully!!!");
        resetData();
    }//GEN-LAST:event_btnOverWriteActionPerformed

    private void btnDuplicateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDuplicateActionPerformed
        // TODO add your handling code here:
        slHandler.addSlangWord(tbSlangWordAddNew.getText(), tbDefinitionAddNew.getText(), 2);
        dlConfirmAddSlangWord.setVisible(false);
        JOptionPane.showMessageDialog(null, "Duplicate slang word successfully!!!");      
        resetData();
    }//GEN-LAST:event_btnDuplicateActionPerformed

    private void btnCloseConfirmAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseConfirmAddActionPerformed
        // TODO add your handling code here:
        dlConfirmAddSlangWord.setVisible(false);
    }//GEN-LAST:event_btnCloseConfirmAddActionPerformed

    private void btnActionQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionQuizActionPerformed
        // TODO add your handling code here:
        List<String> listAnswer = null;
        int answer = rd.nextInt(4);
        correctAnswer = answer;
        if (rdSlangWord.isSelected()){
            listAnswer = slHandler.quizWithSlangWord();
            if (listAnswer.size() == 0){
                return;
            }
            lbQuestion.setText("Which definition is of slang word '" + listAnswer.get(0) + "' ?");
        }
        else{
            listAnswer = slHandler.quizWithDefinition();
            if (listAnswer.size() == 0){
                return;
            }
            lbQuestion.setText("Which slang word is the definition of '" + listAnswer.get(0) + "' ?");
        }
        pnShowContentQuiz.setVisible(true);
        
        if (answer == 0){
            btnAS1.setText(listAnswer.get(1));
            btnAS2.setText(listAnswer.get(2));
            btnAS3.setText(listAnswer.get(3));
            btnAS4.setText(listAnswer.get(4));
        }
        else if (answer == 1){
            btnAS1.setText(listAnswer.get(2));
            btnAS2.setText(listAnswer.get(1));
            btnAS3.setText(listAnswer.get(3));
            btnAS4.setText(listAnswer.get(4));
        }
        else if (answer == 2){
            btnAS1.setText(listAnswer.get(2));
            btnAS2.setText(listAnswer.get(3));
            btnAS3.setText(listAnswer.get(1));
            btnAS4.setText(listAnswer.get(4));
        }
        else{
            btnAS1.setText(listAnswer.get(2));
            btnAS2.setText(listAnswer.get(3));
            btnAS3.setText(listAnswer.get(4));
            btnAS4.setText(listAnswer.get(1));
        } 
    }//GEN-LAST:event_btnActionQuizActionPerformed

    private void btnAS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAS1ActionPerformed
        // TODO add your handling code here:
        if (correctAnswer == 0){
            JOptionPane.showMessageDialog(null, "Congratulations, the answer is absolutely correct !!!!!!");
            resetData();
        }else{
            dlConfirmContinueQuiz.setVisible(true);          
        }
    }//GEN-LAST:event_btnAS1ActionPerformed

    private void btnAS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAS2ActionPerformed
        // TODO add your handling code here:
        if (correctAnswer == 1){
            JOptionPane.showMessageDialog(null, "Congratulations, the answer is absolutely correct !!!!!!");  
            resetData();
        }else{
            dlConfirmContinueQuiz.setVisible(true);
        }
    }//GEN-LAST:event_btnAS2ActionPerformed

    private void btnAS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAS3ActionPerformed
        // TODO add your handling code here:
        if (correctAnswer == 2){
            JOptionPane.showMessageDialog(null, "Congratulations, the answer is absolutely correct !!!!!!");     
            resetData();
        }else{
            dlConfirmContinueQuiz.setVisible(true);          
        }
    }//GEN-LAST:event_btnAS3ActionPerformed

    private void btnAS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAS4ActionPerformed
        // TODO add your handling code here:
        if (correctAnswer == 3){
            JOptionPane.showMessageDialog(null, "Congratulations, the answer is absolutely correct !!!!!!");
            resetData();
        }else{
            dlConfirmContinueQuiz.setVisible(true);
        }
    }//GEN-LAST:event_btnAS4ActionPerformed

    private void btnYesQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesQuizActionPerformed
        // TODO add your handling code here:
        dlConfirmContinueQuiz.setVisible(false);
    }//GEN-LAST:event_btnYesQuizActionPerformed

    private void btnNoQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoQuizActionPerformed
        // TODO add your handling code here:
        dlConfirmContinueQuiz.setVisible(false);
        resetData();
    }//GEN-LAST:event_btnNoQuizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAS1;
    private javax.swing.JButton btnAS2;
    private javax.swing.JButton btnAS3;
    private javax.swing.JButton btnAS4;
    private javax.swing.JButton btnActionAddSlangWord;
    private javax.swing.JButton btnActionQuiz;
    private javax.swing.JButton btnCloseConfirmAdd;
    private javax.swing.JButton btnCloseConfirmDelete;
    private javax.swing.JButton btnCloseConfirmReset;
    private javax.swing.JButton btnDeleteSlangWord;
    private javax.swing.JButton btnDuplicate;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnNoQuiz;
    private javax.swing.JButton btnOkeConfirmDelete;
    private javax.swing.JButton btnOkeConfirmReset;
    private javax.swing.JButton btnOverWrite;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnRandomAction;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearchByDefinition;
    private javax.swing.JButton btnSearchBySlang;
    private javax.swing.JButton btnSearchKeyDefinition;
    private javax.swing.JButton btnSearchKeySlang;
    private javax.swing.JButton btnSearchKeySlangModify;
    private javax.swing.JButton btnUpdateSlangWord;
    private javax.swing.JButton btnYesQuiz;
    private javax.swing.JButton btnaddNewSlangWord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JDialog dlConfirmAddSlangWord;
    private javax.swing.JDialog dlConfirmContinueQuiz;
    private javax.swing.JDialog dlDelete;
    private javax.swing.JDialog dlReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea lbHistoryResult;
    private javax.swing.JTextArea lbQuestion;
    private javax.swing.JTextArea lbResult;
    private javax.swing.JTextArea lbResultDefinition;
    private javax.swing.JTextArea lbResultModify;
    private javax.swing.JTextArea lbResultRandom;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel pnAddNewSlangWord;
    private javax.swing.JPanel pnHistory;
    private javax.swing.JPanel pnMainCard;
    private javax.swing.JPanel pnModify;
    private javax.swing.JPanel pnQuiz;
    private javax.swing.JPanel pnRandom;
    private javax.swing.JPanel pnSearchByDefinition;
    private javax.swing.JPanel pnSearchBySlang;
    private javax.swing.JPanel pnShowContentQuiz;
    private javax.swing.JRadioButton rdDefinition;
    private javax.swing.JRadioButton rdSlangWord;
    private javax.swing.JTextField tbDefinition;
    private javax.swing.JTextArea tbDefinitionAddNew;
    private javax.swing.JTextField tbSlangWord;
    private javax.swing.JTextField tbSlangWordAddNew;
    private javax.swing.JTextField tbSlangWordModify;
    // End of variables declaration//GEN-END:variables
}
