/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Map;
import java.util.TreeMap;
import slang.dictionary.SlangWord;

/**
 *
 * @author Admin
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    
    CardLayout mainCardLayout;
    public HomeFrame() {
        initComponents();
        SlangWord slHandler = new SlangWord();
        this.setLocationRelativeTo(null);
        mainCardLayout = (CardLayout)(pnMainCard.getLayout());
        btnSearchBySlang.setBackground(Color.white);
        //TreeMap<String, String[]> treeData = slHandler.InitData();
//        for (Map.Entry<String, String[]> entry : treeData.entrySet()) {
//           System.out.print(entry.getKey() + "`");
//           for (int i = 0; i < entry.getValue().length; i++)
//               System.out.print(entry.getValue()[i] + "|");
//           System.out.print("\n");
//       }
        
    }
    
    public void resetColorButton(){
        Color defaultColor = new Color(204, 204, 204);
        btnSearchBySlang.setBackground(defaultColor);
        btnSearchByDefinition.setBackground(defaultColor);
        btnHistory.setBackground(defaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelSidebar = new javax.swing.JPanel();
        btnSearchByDefinition = new javax.swing.JButton();
        btnSearchBySlang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        pnMainCard = new javax.swing.JPanel();
        pnSearchBySlang = new javax.swing.JPanel();
        pnSearchByDefinition = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jSplitPane1.setDividerSize(1);

        panelSidebar.setBackground(new java.awt.Color(102, 153, 255));

        btnSearchByDefinition.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchByDefinition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchByDefinition.setText("Tìm kiếm theo definition");
        btnSearchByDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByDefinitionActionPerformed(evt);
            }
        });

        btnSearchBySlang.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchBySlang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchBySlang.setText("Tìm kiếm theo slang word");
        btnSearchBySlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySlangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Slang Dictionnary");

        btnHistory.setBackground(new java.awt.Color(204, 204, 204));
        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHistory.setText("Xem lịch sử tìm kiếm");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearchBySlang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelSidebar);

        pnMainCard.setLayout(new java.awt.CardLayout());

        pnSearchBySlang.setBackground(new java.awt.Color(102, 255, 0));
        pnSearchBySlang.setName(""); // NOI18N

        javax.swing.GroupLayout pnSearchBySlangLayout = new javax.swing.GroupLayout(pnSearchBySlang);
        pnSearchBySlang.setLayout(pnSearchBySlangLayout);
        pnSearchBySlangLayout.setHorizontalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        pnSearchBySlangLayout.setVerticalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pnMainCard.add(pnSearchBySlang, "pnSearchBySlang");

        pnSearchByDefinition.setBackground(new java.awt.Color(255, 0, 0));
        pnSearchByDefinition.setName(""); // NOI18N

        javax.swing.GroupLayout pnSearchByDefinitionLayout = new javax.swing.GroupLayout(pnSearchByDefinition);
        pnSearchByDefinition.setLayout(pnSearchByDefinitionLayout);
        pnSearchByDefinitionLayout.setHorizontalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 625, Short.MAX_VALUE)
        );
        pnSearchByDefinitionLayout.setVerticalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pnMainCard.add(pnSearchByDefinition, "pnSearchByDefinition");

        jSplitPane1.setRightComponent(pnMainCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 830, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBySlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySlangActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchBySlang");
        resetColorButton();
        btnSearchBySlang.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchBySlangActionPerformed

    private void btnSearchByDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByDefinitionActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchByDefinition");
        resetColorButton();
        btnSearchByDefinition.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchByDefinitionActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnSearchByDefinition;
    private javax.swing.JButton btnSearchBySlang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel pnMainCard;
    private javax.swing.JPanel pnSearchByDefinition;
    private javax.swing.JPanel pnSearchBySlang;
    // End of variables declaration//GEN-END:variables
}
