/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import java.awt.Color;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import slang.dictionary.SlangWord;

/**
 *
 * @author Admin
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrame
     */
    
    CardLayout mainCardLayout;
    SlangWord slHandler = null;
    public HomeFrame() {
        initComponents();
        slHandler = new SlangWord();
        this.setLocationRelativeTo(null);
        mainCardLayout = (CardLayout)(pnMainCard.getLayout());
        btnSearchBySlang.setBackground(Color.white);
        Border border = BorderFactory.createLineBorder(Color.BLACK);
        lbResult.setBorder(BorderFactory.createCompoundBorder(border, 
            BorderFactory.createEmptyBorder(20, 20, 10, 10)));
    }
    
    public void resetColorButton(){
        Color defaultColor = new Color(204, 204, 204);
        btnSearchBySlang.setBackground(defaultColor);
        btnSearchByDefinition.setBackground(defaultColor);
        btnHistory.setBackground(defaultColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelSidebar = new javax.swing.JPanel();
        btnSearchByDefinition = new javax.swing.JButton();
        btnSearchBySlang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        addNewSlangWord = new javax.swing.JButton();
        btnModify1 = new javax.swing.JButton();
        btnRandom = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnMainCard = new javax.swing.JPanel();
        pnSearchBySlang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tbSlangWord = new javax.swing.JTextField();
        btnSearchKeySlang = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbResult = new javax.swing.JTextArea();
        pnSearchByDefinition = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerSize(1);

        panelSidebar.setBackground(new java.awt.Color(102, 153, 255));

        btnSearchByDefinition.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchByDefinition.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchByDefinition.setText("Tìm kiếm theo definition");
        btnSearchByDefinition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchByDefinitionActionPerformed(evt);
            }
        });

        btnSearchBySlang.setBackground(new java.awt.Color(204, 204, 204));
        btnSearchBySlang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearchBySlang.setText("Tìm kiếm theo slang word");
        btnSearchBySlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBySlangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Slang Dictionnary");

        btnHistory.setBackground(new java.awt.Color(204, 204, 204));
        btnHistory.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnHistory.setText("Xem lịch sử tìm kiếm");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        addNewSlangWord.setBackground(new java.awt.Color(204, 204, 204));
        addNewSlangWord.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        addNewSlangWord.setText("Thêm slang word");
        addNewSlangWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewSlangWordActionPerformed(evt);
            }
        });

        btnModify1.setBackground(new java.awt.Color(204, 204, 204));
        btnModify1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnModify1.setText("Chỉnh sửa và xóa slang word");
        btnModify1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModify1ActionPerformed(evt);
            }
        });

        btnRandom.setBackground(new java.awt.Color(204, 204, 204));
        btnRandom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRandom.setText("Random slang word");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        btnQuiz.setBackground(new java.awt.Color(204, 204, 204));
        btnQuiz.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuiz.setText("Đố vui");
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(255, 51, 51));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReset.setText("Reset danh sách slang words");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addNewSlangWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnModify1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSearchBySlang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQuiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnSearchBySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchByDefinition, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModify1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelSidebar);

        pnMainCard.setLayout(new java.awt.CardLayout());

        pnSearchBySlang.setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nhập từ khóa:");

        tbSlangWord.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSearchKeySlang.setBackground(new java.awt.Color(102, 153, 255));
        btnSearchKeySlang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSearchKeySlang.setText("Search");
        btnSearchKeySlang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSearchKeySlang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchKeySlangActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Kết quả tìm kiếm");

        lbResult.setBackground(new java.awt.Color(102, 153, 255));
        lbResult.setColumns(20);
        lbResult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbResult.setLineWrap(true);
        lbResult.setRows(5);
        lbResult.setWrapStyleWord(true);
        lbResult.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(lbResult);

        javax.swing.GroupLayout pnSearchBySlangLayout = new javax.swing.GroupLayout(pnSearchBySlang);
        pnSearchBySlang.setLayout(pnSearchBySlangLayout);
        pnSearchBySlangLayout.setHorizontalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                .addGroup(pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tbSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearchKeySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel3)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnSearchBySlangLayout.setVerticalGroup(
            pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSearchBySlangLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnSearchBySlangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbSlangWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchKeySlang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pnMainCard.add(pnSearchBySlang, "pnSearchBySlang");

        pnSearchByDefinition.setBackground(new java.awt.Color(255, 0, 0));
        pnSearchByDefinition.setName(""); // NOI18N

        javax.swing.GroupLayout pnSearchByDefinitionLayout = new javax.swing.GroupLayout(pnSearchByDefinition);
        pnSearchByDefinition.setLayout(pnSearchByDefinitionLayout);
        pnSearchByDefinitionLayout.setHorizontalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        pnSearchByDefinitionLayout.setVerticalGroup(
            pnSearchByDefinitionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );

        pnMainCard.add(pnSearchByDefinition, "pnSearchByDefinition");

        jSplitPane1.setRightComponent(pnMainCard);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchBySlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBySlangActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchBySlang");
        resetColorButton();
        btnSearchBySlang.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchBySlangActionPerformed

    private void btnSearchByDefinitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchByDefinitionActionPerformed

        mainCardLayout.show(pnMainCard, "pnSearchByDefinition");
        resetColorButton();
        btnSearchByDefinition.setBackground(Color.white);
    }//GEN-LAST:event_btnSearchByDefinitionActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void addNewSlangWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewSlangWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addNewSlangWordActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRandomActionPerformed

    private void btnModify1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModify1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModify1ActionPerformed

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSearchKeySlangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchKeySlangActionPerformed
        // TODO add your handling code here:
        if (tbSlangWord.getText().compareTo("") == 0){
            return;
        }
        lbResult.setText("");
        String[] listDefinition = slHandler.getDataBySlangWord(tbSlangWord.getText());
        if (listDefinition == null){           
            lbResult.setText("Rất tiếc, không tìm thấy Slang word nào với từ khóa '" + 
                    tbSlangWord.getText() + "' :((");
            lbResult.setForeground(Color.RED);
        }
        else{
            String result = "Definitons of '" + tbSlangWord.getText() + "': ";
            for (int i = 0; i < listDefinition.length; i++){
                result += listDefinition[i];
                if (i != listDefinition.length - 1){
                    result += ",";
                }
            }
            lbResult.setText(result);
            lbResult.setForeground(Color.BLACK);
        }
        tbSlangWord.setText("");
    }//GEN-LAST:event_btnSearchKeySlangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewSlangWord;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnModify1;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JButton btnRandom;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearchByDefinition;
    private javax.swing.JButton btnSearchBySlang;
    private javax.swing.JButton btnSearchKeySlang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea lbResult;
    private javax.swing.JPanel panelSidebar;
    private javax.swing.JPanel pnMainCard;
    private javax.swing.JPanel pnSearchByDefinition;
    private javax.swing.JPanel pnSearchBySlang;
    private javax.swing.JTextField tbSlangWord;
    // End of variables declaration//GEN-END:variables
}
